---
title: "Machine Learning With R"
author: "Nicholas Moore"
date: "2022-08-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## {.tabset .tabset-fade} 

# <span style="color:red"> Supervised Learning </span>
- Provide data directly to the machine. Provide features which can be labeled 
- The data is known as training data, and consists of a set of training examples. Each training example has one or more inputs and the desired output, also known as a supervisory signal. In the mathematical model, each training example is represented by an array or vector, sometimes called a feature vector, and the training data is represented by a matrix.
* (Ex: weight of coin is a feature & coin type is the label)
- The answer is already known with labeled data and is fed to the ML system to predict a value or feature.
* Facial recognition (face or not face).

### <span style="color:darkgreen"> Active Learning </span>

### <span style="color:darkgreen"> Classification / Categorization </span>
- Discrete data.
- Classification algorithms are used when the outputs are restricted to a limited set of values.
* Algorithm that filters emails, the input would be an incoming email, and the output would be the name of the folder in which to file the email.

### <span style="color:darkgreen"> Regression </span>
- Numerical or Continuous data.
- Used for prediction and forecasting. Determines casual relationship between indpendent and dependent variables.
- Regression algorithms are used when the outputs may have any numerical value within a range.
- Regression predictions can be evaluated using root mean squared error, whereas classification predictions cannot.

### <span style="color:darkgreen"> Similarity Learning </span>
- Area of supervised machine learning closely related to regression and classification, but the goal is to learn from examples using a similarity function that measures how similar or related two objects are.
*  Applications in ranking, recommendation systems, visual identity tracking, face verification, and speaker verification.

# <span style="color:red"> Unsupervised Learning </span>
- ML without labeled data provided. Clusters are often formed to pair groups of similar features.
- The result is not known, we approach with little or No knowledge of what the result would be, the machine is expected to find the hidden patterns and structure in unlabelled data on their own.
- Unsupervised learning models are built to detect unusual behavior in transactions which is not detected previously. Unsupervised learning models involve self-learning that helps in finding hidden patterns in transactions. In this type, the model tries to learn by itself, analyzes the available data, and tries to find the similarities and dissimilarities between the occurrences of transactions. This helps in detecting fraudulent activities.
* Fraud detection, Email Phishing, Payment Fraud, ID Document Forgery, Identity Theft
# Reinforcement Learning
- ML based on postive and negative feedback.

### <span style="color:darkgreen"> Clustering </span>

### <span style="color:darkgreen"> Association </span>

**Sources**
[Amnah Khatun](https://chatbotsmagazine.com/lets-know-supervised-and-unsupervised-in-an-easy-way-9168363e06ab),
[Javier Fernandez](https://towardsdatascience.com/introduction-to-regression-analysis-9151d8ac14b3),
[Wikipedia](https://en.wikipedia.org/wiki/Machine_learning#Supervised_learning)